RelativeURLs=true
CanonifyURLs=true
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Wild Rydes Asynchronous Messaging Workshop"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= false

uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
  editURL = "https://code.amazon.com/packages/AwsSaDeMsgPtnMcrSrv/trees/mainline/--/workshop/content/"
  description = "Wild Rydes Asynchronous Messaging Workshop"
  author = "Jane Architect"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableSearch = false
  disableAssetsBusting = true
  disableLanguageSwitchingButton = false
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true

[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/aws-samples/asynchronous-messaging-workshop/"
weight = 10